version: '3'
services:
  sc-tool:
    build: .
    container_name: sc-tool
    volumes:
      - ./sol:/sol
      - ./solana-config:/root/.config/solana
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
